Add files via upload
added files on pages. via site, not command line because of:
Enter passphrase for key '/c/Users/admin/.ssh/id_rsa':
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.